### ISSUE TITLE
# Evaluate concept of updating master data in streaming job

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#117]
- har vi regnet nok på størrelse af tid for indlæsning af master data? V 
- vi kan nok optimere hvornår vi indlæser master data (fx ikke når der er nye master data, men når der er ændringer i master data, der gælder for et tidspuntk, der ligger mindre end 5 min ud i fremtiden) V
- hvor lang tid står jobbet stille pga. genindlæsning af master data i produktion? Hvilke datamængder skal vi antage? Antal records (husk, at der kan være mange pr målepunkt pga datoer)? Hvor mange data (husk, at vi mangler mange valideringsregler)?

Bottom line: Holder vores concept/implementering også i produktion?

**Comment by bemwen** [comment]
Consider whether we actually need to be as fault tolerant as before in regards to the 5-minute windows.

It was primarily an issue because data could be stored wrongly and give wrong aggregations. 

But now that we do not same enrichment data to deltalake, it is "just" a matter of validation where something might be validated wrongly in a small window.

**Comment by PerTHenriksen** [comment]
Closed, replaced by #189
