### ISSUE TITLE
Databricks can receive and store time series (migration)

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#36]
**Synopsis**
The business requests the time series streaming to be moved to the new open-source repo for the time series.

**Scope**
Only the Databricks streaming job and unit tests.
ODS is not migrated, we'll just use a hardcoded CSV master data file.
Storing in CosmosDb representation the Post Office is out of scope as Post Office has been redesigned.

**Acceptance Criteria**
AC 1: Time series unit tests pass
AC 2: Valid time-series sent to event hub are stored in Delta Lake

The following criteria apply if validation is included in the migration.

AC 3: Time-series are validated against test master data in the CSV file
AC 4: Invalid time series are not stored in Delta Lake

**Comment by HenrikSommer** [comment]
Test procedure

AC 1: 
Test completion of acceptance criteria 1 by viewing completion of Time series unit tests in pipeline for T-environment (Test environment).

Completion of acceptance criteria 2 - 4 rely on valid and invalid messages sent to eventhub used by timeseries databricks streaming job.

You can send messages to eventhub used by timeseries databricks streaming job using Visual Studio Code with extension "Azure Eventhub Explorer":
- With "Azure Eventhub Explorer" installed hit "Ctrl + Shift + p"
- Search for and use "Azure: Sign in"
- Search for and use "EventHub: Select Event Hub":
	- select subscription: "subscr-green-T-001"
	- select resource group: "rg-Datahub-TimeSeries-T"
	- select eventhub: "evhnm-received-queue-time-endk-t"
- Search for and use "EventHub: Send Message To Event Hub"
	- copy content of streamingUtils/testdata/vr200_invalid_time_series.template.json and send
	- copy content of streamingUtils/testdata/single_valid_time_series.template.json and send

AC 3: 
- Open Azure Portal and select resource group "rg-DataHub-TimeSeries-T"
- Select Databricks "dbw-time-endk-t" and click "Launch Workspace"
- Select "Jobs" in left menu and select "StreamingJob"
- In "Active Runs" make sure there is a running job
- Click "View details" and then "Logs"
- In "Standard logs" look for "Continuing with current master data because they have not been updated in ODS......"

AC 2 and 4:
- Open Azure Portal and select resource group "rg-DataHub-TimeSeries-T"
- Select "datatimeendkt" and then "Containers"
- Select messagedata --> delta/meter-data
- Look for the folder year=2020/month=11/day=12
- Look for a *.parquet file containing the expected mRID from single_valid_time_series.template.json (AC 2)
- Make sure there is no *.parquet file containing the expected mRID from vr200_invalid_time_series.template.json (AC 4)

**Comment by prtandrup** [comment]
This story use the old time series format, which has become obsolete due to the introduction of the new format (#38).
Therefore, the AC2-4 cannot be tested with the old format, but will be tested with the new format instead.
AC1) was verified.
I suggest to close this ticket.

**Comment by BjarkeMeier** [comment]
I support the suggestion to close this story. There is no point in keeping it around or testing it when the new naming and format have already been implemented.
